import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "@/components/Navbar/Nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <Nav />
        </header>
        <div className="relative">
          <video
            className="h-screen w-full object-cover -z-10 absolute top-0 "
            loop
            autoPlay
            muted
          >
            <source src="/video/bg.mp4" type="video/mp4" />
          </video>
          <div className="bg-gradient-to-r from-black to-transparent h-screen w-full absolute opacity-80 shadow-2xl"></div>
        </div>

        <div className="mx-10 ">{children}</div>
      </body>
    </html>
  );
}
